### ISSUE TITLE
Error: This Socket Is Closed

### ISSUE THREAD

**Issue by SamBoyd** [tcort/wkhtmltox#11]
Getting an error when running the example html to pdf web server. The problem seems to appear on OS X and linux

```
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at Socket._writeGeneric (net.js:702:18)
    at Socket._write (net.js:757:8)
    at doWrite (_stream_writable.js:406:12)
    at writeOrBuffer (_stream_writable.js:392:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at IncomingMessage.ondata (_stream_readable.js:646:20)
    at IncomingMessage.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at IncomingMessage.Readable.push (_stream_readable.js:213:10)
Emitted 'error' event at:
    at Socket.onerror (_stream_readable.js:670:12)
    at Socket.emit (events.js:180:13)
    at onwriteError (_stream_writable.js:421:12)
    at onwrite (_stream_writable.js:449:5)
    at Socket.destroy (internal/streams/destroy.js:12:7)
    at Socket._writeGeneric (net.js:702:10)
    at Socket._write (net.js:757:8)
    [... lines matching original stack trace ...]
    at Socket.Writable.write (_stream_writable.js:290:11)
```

**Comment by SamBoyd** [comment]
Seems to only happen when running via my IDE (webstorm) and works fine in a normal terminal
